spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.146.206.158:3306/test
    username: root
    password: 9&Nq#3Gz@Xv$BpT
    hikari:
      auto-commit: true
      minimum-idle: 10
      maximum-pool-size: 60
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1
  redis:
    host: 8.146.206.158
    port: 6379
    password: root
    database: 5
    jedis:
      pool:
        max-active: 10
        max-idle: 1
        min-idle: 1
        max-wait: 1000ms